import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import { Providers } from "./providers";

import CartNavbar from "./cart/CartNavbar.jsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Doaa Company",
  description: "Generated by Doaa",
  icons: {
    icon: "/companyLogo.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css"
        />
      </head>
      <body className={inter.className}>
        <Providers>
          <div className="max-w-7xl mx-4 xl:mx-auto">
            <nav className="flex h-14 items-center justify-between">
              <div className="logo outline-0">
                <h1 className="text-2xl font-bold text-[#551540de] tracking-wide">
                  <Link href="/" className="outline-0">
                    Doaa
                    <span className="text-gray-500 font-normal">Company</span>
                  </Link>
                </h1>
              </div>
              <CartNavbar />
            </nav>
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
